[tool.poetry]
name = "mariskavanwilligen-blog"
version = "0.1.0"
description = ""
authors = ["Mariska van Willigen"]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
